"use strict";
(() => {
  const esc=(v)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const safeUrl=(v)=>/^https:\/\//i.test(String(v??""))?String(v):"#";
  const money=(v)=>v==null?"":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
  const kindLabel=(k)=>({contract_opportunity:"contract",funding_opportunity:"funding",federal_award_action:"award activity",stakeholder_meeting:"OIRA meeting",legislative_update:"legislation"}[k]||k||"federal activity");
  const edgeLabel=(e)=>({early:"early signal",new:"newly discovered","high-fit":"high fit",standard:"matched"}[e]||"matched");
  const laneMeta={act_now:["Act now","Open contracts and funding where a near-term action can still change the outcome."],market_intelligence:["Market intelligence","Awards and government activity that reveal where money, demand and capacity are moving."],policy_signals:["Policy signals","Legislation, regulatory meetings and upstream actions that may reshape a market."]};
  function card(item){const close=item.days_to_close==null?"":`<span>${item.days_to_close===0?"closes today":`closes in ${item.days_to_close}d`}</span>`; const amount=item.amount==null?"":`<span>${esc(money(item.amount))}</span>`; const reasons=(item.reasons||[]).slice(0,6).map(x=>`<li>${esc(x)}</li>`).join(""); const profiles=(item.profiles||[]).map(x=>`<span class="badge">${esc(x.replaceAll("_"," "))}</span>`).join(" "); const components=Object.entries(item.score_components||{}).filter(([,v])=>Number(v)>0).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([k,v])=>`${k.replaceAll("_"," ")} +${v}`).join(" · "); return `<article class="card opportunity-card"><div class="card-top"><div><span class="badge high">${esc(edgeLabel(item.edge))}</span><h3>${esc(item.title||"Federal opportunity")}</h3></div><span class="lifecycle">${esc(kindLabel(item.kind))}</span></div><p class="meta-line">${esc(item.agency||"Federal agency")} · ${esc(item.event_date||"")}</p><p class="meta-line">${amount}${close}</p><div>${profiles}</div><p class="muted"><strong>Why it surfaced:</strong> ${esc(components||`score ${item.score}`)}</p><ul class="muted">${reasons}</ul><details><summary>Scoring breakdown · ${esc(item.score)}</summary><div class="diagnostic-rows">${Object.entries(item.score_components||{}).filter(([,v])=>Number(v)>0).map(([k,v])=>`<div><span>${esc(k.replaceAll("_"," "))}</span><strong>+${esc(v)}</strong></div>`).join("")}</div></details><a class="primary-link" href="${esc(safeUrl(item.official_url))}" target="_blank" rel="noopener noreferrer">Official record ↗</a></article>`;}
  function lane(key,items){const [title,desc]=laneMeta[key]; return `<div class="opportunity-lane"><div class="section-heading"><div><div class="eyebrow">${esc(key.replaceAll("_"," "))}</div><h3>${esc(title)}</h3><p class="muted">${esc(desc)}</p></div><span class="count">${items.length}</span></div><div class="cards">${items.length?items.slice(0,8).map(card).join(""):`<div class="quiet-state compact"><strong>Nothing urgent here.</strong><span>No fresh matches in this lane.</span></div>`}</div></div>`;}
  async function load(){const list=document.getElementById("opportunity-list"),count=document.getElementById("opportunity-count"); if(!list||!count)return; try{const response=await fetch("../data/outputs/current/opportunities_today.json",{cache:"no-store"}); if(!response.ok)throw new Error(`HTTP ${response.status}`); const payload=await response.json(),lanes=payload.lanes||{}; count.textContent=String((payload.items||[]).length); list.innerHTML=["act_now","market_intelligence","policy_signals"].map(k=>lane(k,lanes[k]||[])).join("");}catch(error){count.textContent="—";list.innerHTML=`<div class="empty">Opportunities feed unavailable: ${esc(error.message)}</div>`;}}
  load();
})();
